<BlockWindow>:
    MDBoxLayout:
        orientation: "vertical"

        
    MDBottomAppBar:
        MDToolbar:
            title: "Website Archives"
            icon: "transfer-left"
            on_action_button: app.change_screen("main_menu", direction='right', mode='push')
            type: "bottom"
            left_action_items: [["archive"]]
            mode: "free-end"
                                    